version: "3"

networks:
  geoquizz.net:
    driver: bridge

services:
  MySql:
    container_name: MySql
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=geoquizz-local
      - MYSQL_PASSWORD=geoquizz-local
      - MYSQL_DATABASE=geoquizz
    ports:
      - "3307:3306"
    networks:
      - geoquizz.net

  PhpMyAdmin:
    container_name: PhpMyAdmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8000:80"
    networks:
      - geoquizz.net
    links:
      - MySql:db

  API-player:
    container_name: API-player
    image: canals/php:latest
    environment:
      - VHOST_HOSTNAME=api.player.local
      - VHOST_DOCROOT=/var/www/api
    ports:
      - "19180:80"
      - "19143:443"
    volumes:
      - ./Player/api:/var/www/api
      - ./Player/src:/var/www/src
    working_dir: /var/www/src
    networks:
      - geoquizz.net
    links:
      - MySql:db

  API-backoffice:
    container_name: API-backoffice
    image: canals/php:latest
    environment:
      - VHOST_HOSTNAME=api.backoffice.local
      - VHOST_DOCROOT=/var/www/api
    ports:
      - "19280:80"
      - "19243:443"
    volumes:
      - ./Backoffice/api:/var/www/api
      - ./Backoffice/src:/var/www/src
    working_dir: /var/www/src
    networks:
      - geoquizz.net
    links:
      - MySql:db

  API-mobile:
    container_name: API-mobile
    image: canals/php:latest
    environment:
      - VHOST_HOSTNAME=api.mobile.local
      - VHOST_DOCROOT=/var/www/api
    ports:
      - "19380:80"
      - "19343:443"
    volumes:
      - ./Mobile/api:/var/www/api
      - ./Mobile/src:/var/www/src
    working_dir: /var/www/src
    networks:
      - geoquizz.net
    links:
      - MySql:db
